import Head from 'next/head';
import React from 'react';

export const HeadComponent = () => {
  return (
    <Head>
      <title>Pokédex</title>
      <meta name="description" content="Pokédex generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/pikachu.png" />
    </Head>
  );
}
